### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by HeliangCN** [botcity-dev/botcity-framework-core#23]
Hi @hhslepicka, I'm having trouble importing the project.  
`Could not find artifact org.marvinproject:MarvinFramework:pom:2.0 in central (https://repo.maven.apache.org/maven2)`
`Could not find artifact org.marvinproject:MarvinPlugins:pom:2.0 in central (https://repo.maven.apache.org/maven2)`
![1657701388087](https://user-images.githubusercontent.com/34956325/178689725-1f150882-4000-47c0-b7ab-6e98dfe00fa9.png)

I can't find it in https://mvnrepository.com either
![1657701538149](https://user-images.githubusercontent.com/34956325/178689817-ba2316c0-bbf6-4d40-ac33-b9457df5e9a4.png)
![1657701651438](https://user-images.githubusercontent.com/34956325/178690248-f7058bed-ea95-4bea-a360-04ebe86b621d.png)

**Comment by hhslepicka** [comment]
@HeliangCN, sorry for the late reply.
All the dependencies are now available via our Nexus repository. We will soon add them to Maven Central as well but for now you can do the following on your `pom.xml`:

```
    <repositories>
        <repository>
            <id>nexus-botcity-public</id>
            <url>https://devtools.botcity.dev:8081/repository/botcity-public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

And pull the dependencies from there.

Feel free to reopen the issue in case this didn't work for your code.
